language: python

python:
  - 2.7

services:
  - docker

install:
  - docker build -t ingluife/flutter:latest .
  - docker run -d -p 127.0.0.1:80:80 --name flutter-container ingluife/flutter:latest

script:
  - docker ps | grep -q flutter-container
